AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create IAM Role, ECR repository, and Lambda Function from Docker image

Resources:
  MyCfnRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MyCfnPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: '*'

  # EthanCfnRepository:
  #   Type: 'AWS::ECR::Repository'
  #   Properties:
  #     RepositoryName: ethan-cfn-test

  MyCfnFunction:
    Type: 'AWS::Lambda::Function'
    DependsOn: 
     - MyCfnRole
    Properties:
      FunctionName: <your-lambda-function>
      Role: !GetAtt MyCfnRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub "<account-id>.dkr.ecr.<region>.amazonaws.com/<your-ecr-repo>:<image-name>"
      MemorySize: 384
      Timeout: 900
    Metadata:
      aws:asset:path: asset.<image-name>
      aws:asset:dockerfile-path: Dockerfile
      aws:asset:property: Code.ImageUri
    
