Resources:
  LambdaBasicRole77814A6C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action: sts:AssumeRole
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: AssumeRolePolicy
      RoleName: lambda-basic-role
    Metadata:
      aws:cdk:path: AwsCdkTestStack/LambdaBasicRole/Resource
  MyLambdaFunction67CCA873:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Sub: <your-aws-account>.dkr.ecr.<your-region>.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-<your-aws-account>-<your-region>:c10e836856f3dcb40096deb8c43c17a16c5967672f2a6411b3fdfba7ecc89fd1
      FunctionName: my-lambda-function
      MemorySize: 384
      PackageType: Image
      Role:
        Fn::GetAtt:
          - LambdaBasicRole77814A6C
          - Arn
      Timeout: 900
    DependsOn:
      - LambdaBasicRole77814A6C
    Metadata:
      aws:cdk:path: AwsCdkTestStack/MyLambdaFunction/Resource
      aws:asset:path: asset.c10e836856f3dcb40096deb8c43c17a16c5967672f2a6411b3fdfba7ecc89fd1
      aws:asset:dockerfile-path: Dockerfile
      aws:asset:property: Code.ImageUri
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OXQrCMBCEz+J7ulqrB/AHwTeJByjbdK1rm0SSFCmhd7epCj7NMvMxs2vINwWsFvjymarbrOMK4jWgasVklZFRQ5S2I3G4maSj6FBXNUI8WtWSO2ts6NQbFdiaBP3uUZByJXpPwcMfu0tOykDS03oO1g179FOxJG97p0jMyPREw6aZd7/BKC5DuFuzLCDPYbt4eObM9SawJpAffQNtxJXE0QAAAA==
    Metadata:
      aws:cdk:path: AwsCdkTestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion